// Helper function to get country code from country name for flag display
const getCountryCode = (countryName: string): string | null => {
  // If it's already a 2-letter code, return it uppercase
  if (countryName.length === 2) {
    return countryName.toUpperCase();
  }

  const countryMap: Record<string, string> = {
    // North America
    "United States": "US",
    Canada: "CA",
    Mexico: "MX",
    Guatemala: "GT",
    Belize: "BZ",
    "El Salvador": "SV",
    Honduras: "HN",
    Nicaragua: "NI",
    "Costa Rica": "CR",
    Panama: "PA",

    // Europe
    "United Kingdom": "GB",
    Ireland: "IE",
    France: "FR",
    Spain: "ES",
    Portugal: "PT",
    Italy: "IT",
    Germany: "DE",
    Netherlands: "NL",
    Belgium: "BE",
    Luxembourg: "LU",
    Switzerland: "CH",
    Austria: "AT",
    "Czech Republic": "CZ",
    Slovakia: "SK",
    Poland: "PL",
    Hungary: "HU",
    Slovenia: "SI",
    Croatia: "HR",
    "Bosnia and Herzegovina": "BA",
    Serbia: "RS",
    Montenegro: "ME",
    Albania: "AL",
    "North Macedonia": "MK",
    Bulgaria: "BG",
    Romania: "RO",
    Moldova: "MD",
    Ukraine: "UA",
    Belarus: "BY",
    Lithuania: "LT",
    Latvia: "LV",
    Estonia: "EE",
    Finland: "FI",
    Sweden: "SE",
    Norway: "NO",
    Denmark: "DK",
    Iceland: "IS",
    Greece: "GR",
    Cyprus: "CY",
    Malta: "MT",
    "San Marino": "SM",
    "Vatican City": "VA",
    Monaco: "MC",
    Liechtenstein: "LI",
    Andorra: "AD",

    // Asia
    Russia: "RU",
    China: "CN",
    Japan: "JP",
    "South Korea": "KR",
    "North Korea": "KP",
    Mongolia: "MN",
    Kazakhstan: "KZ",
    Kyrgyzstan: "KG",
    Tajikistan: "TJ",
    Uzbekistan: "UZ",
    Turkmenistan: "TM",
    Afghanistan: "AF",
    Pakistan: "PK",
    India: "IN",
    Nepal: "NP",
    Bhutan: "BT",
    Bangladesh: "BD",
    "Sri Lanka": "LK",
    Maldives: "MV",
    Myanmar: "MM",
    Thailand: "TH",
    Laos: "LA",
    Vietnam: "VN",
    Cambodia: "KH",
    Malaysia: "MY",
    Singapore: "SG",
    Brunei: "BN",
    Indonesia: "ID",
    Philippines: "PH",
    "East Timor": "TL",
    Taiwan: "TW",
    "Hong Kong": "HK",
    Macau: "MO",

    // Middle East
    Turkey: "TR",
    Georgia: "GE",
    Armenia: "AM",
    Azerbaijan: "AZ",
    Iran: "IR",
    Iraq: "IQ",
    Syria: "SY",
    Lebanon: "LB",
    Jordan: "JO",
    Israel: "IL",
    Palestine: "PS",
    "Saudi Arabia": "SA",
    Yemen: "YE",
    Oman: "OM",
    "United Arab Emirates": "AE",
    Qatar: "QA",
    Bahrain: "BH",
    Kuwait: "KW",

    // Africa
    Egypt: "EG",
    Libya: "LY",
    Tunisia: "TN",
    Algeria: "DZ",
    Morocco: "MA",
    Sudan: "SD",
    "South Sudan": "SS",
    Ethiopia: "ET",
    Eritrea: "ER",
    Djibouti: "DJ",
    Somalia: "SO",
    Kenya: "KE",
    Uganda: "UG",
    Tanzania: "TZ",
    Rwanda: "RW",
    Burundi: "BI",
    Congo: "CG",
    "Democratic Republic of the Congo": "CD",
    "Central African Republic": "CF",
    Chad: "TD",
    Cameroon: "CM",
    Nigeria: "NG",
    Niger: "NE",
    Mali: "ML",
    "Burkina Faso": "BF",
    Ghana: "GH",
    Togo: "TG",
    Benin: "BJ",
    "Ivory Coast": "CI",
    Liberia: "LR",
    "Sierra Leone": "SL",
    Guinea: "GN",
    "Guinea-Bissau": "GW",
    Senegal: "SN",
    Gambia: "GM",
    Mauritania: "MR",
    "Cape Verde": "CV",
    "Sao Tome and Principe": "ST",
    "Equatorial Guinea": "GQ",
    Gabon: "GA",
    Angola: "AO",
    Zambia: "ZM",
    Zimbabwe: "ZW",
    Botswana: "BW",
    Namibia: "NA",
    "South Africa": "ZA",
    Lesotho: "LS",
    Swaziland: "SZ",
    Mozambique: "MZ",
    Madagascar: "MG",
    Mauritius: "MU",
    Seychelles: "SC",
    Comoros: "KM",
    Malawi: "MW",

    // South America
    Brazil: "BR",
    Argentina: "AR",
    Chile: "CL",
    Peru: "PE",
    Ecuador: "EC",
    Colombia: "CO",
    Venezuela: "VE",
    Guyana: "GY",
    Suriname: "SR",
    Bolivia: "BO",
    Paraguay: "PY",
    Uruguay: "UY",

    // Oceania
    Australia: "AU",
    "New Zealand": "NZ",
    "Papua New Guinea": "PG",
    Fiji: "FJ",
    "Solomon Islands": "SB",
    Vanuatu: "VU",
    "New Caledonia": "NC",
    Samoa: "WS",
    Tonga: "TO",
    Kiribati: "KI",
    Palau: "PW",
    "Marshall Islands": "MH",
    Micronesia: "FM",
    Nauru: "NR",
    Tuvalu: "TV",

    // Caribbean
    Cuba: "CU",
    Jamaica: "JM",
    Haiti: "HT",
    "Dominican Republic": "DO",
    "Puerto Rico": "PR",
    "Trinidad and Tobago": "TT",
    Barbados: "BB",
    "Saint Vincent and the Grenadines": "VC",
    Grenada: "GD",
    "Saint Lucia": "LC",
    Dominica: "DM",
    "Antigua and Barbuda": "AG",
    "Saint Kitts and Nevis": "KN",
    Bahamas: "BS",
  };

  return countryMap[countryName] || null;
};

// Helper function to get country name from country code
const getCountryName = (countryInput: string): string => {
  // If it's already a full country name, return it
  if (countryInput.length > 2) {
    return countryInput;
  }

  const codeToNameMap: Record<string, string> = {
    // North America
    US: "United States",
    CA: "Canada",
    MX: "Mexico",
    GT: "Guatemala",
    BZ: "Belize",
    SV: "El Salvador",
    HN: "Honduras",
    NI: "Nicaragua",
    CR: "Costa Rica",
    PA: "Panama",

    // Europe
    GB: "United Kingdom",
    IE: "Ireland",
    FR: "France",
    ES: "Spain",
    PT: "Portugal",
    IT: "Italy",
    DE: "Germany",
    NL: "Netherlands",
    BE: "Belgium",
    LU: "Luxembourg",
    CH: "Switzerland",
    AT: "Austria",
    CZ: "Czech Republic",
    SK: "Slovakia",
    PL: "Poland",
    HU: "Hungary",
    SI: "Slovenia",
    HR: "Croatia",
    BA: "Bosnia and Herzegovina",
    RS: "Serbia",
    ME: "Montenegro",
    AL: "Albania",
    MK: "North Macedonia",
    BG: "Bulgaria",
    RO: "Romania",
    MD: "Moldova",
    UA: "Ukraine",
    BY: "Belarus",
    LT: "Lithuania",
    LV: "Latvia",
    EE: "Estonia",
    FI: "Finland",
    SE: "Sweden",
    NO: "Norway",
    DK: "Denmark",
    IS: "Iceland",
    GR: "Greece",
    CY: "Cyprus",
    MT: "Malta",
    SM: "San Marino",
    VA: "Vatican City",
    MC: "Monaco",
    LI: "Liechtenstein",
    AD: "Andorra",

    // Asia
    RU: "Russia",
    CN: "China",
    JP: "Japan",
    KR: "South Korea",
    KP: "North Korea",
    MN: "Mongolia",
    KZ: "Kazakhstan",
    KG: "Kyrgyzstan",
    TJ: "Tajikistan",
    UZ: "Uzbekistan",
    TM: "Turkmenistan",
    AF: "Afghanistan",
    PK: "Pakistan",
    IN: "India",
    NP: "Nepal",
    BT: "Bhutan",
    BD: "Bangladesh",
    LK: "Sri Lanka",
    MV: "Maldives",
    MM: "Myanmar",
    TH: "Thailand",
    LA: "Laos",
    VN: "Vietnam",
    KH: "Cambodia",
    MY: "Malaysia",
    SG: "Singapore",
    BN: "Brunei",
    ID: "Indonesia",
    PH: "Philippines",
    TL: "East Timor",
    TW: "Taiwan",
    HK: "Hong Kong",
    MO: "Macau",

    // Middle East
    TR: "Turkey",
    GE: "Georgia",
    AM: "Armenia",
    AZ: "Azerbaijan",
    IR: "Iran",
    IQ: "Iraq",
    SY: "Syria",
    LB: "Lebanon",
    JO: "Jordan",
    IL: "Israel",
    PS: "Palestine",
    SA: "Saudi Arabia",
    YE: "Yemen",
    OM: "Oman",
    AE: "United Arab Emirates",
    QA: "Qatar",
    BH: "Bahrain",
    KW: "Kuwait",

    // Africa
    EG: "Egypt",
    LY: "Libya",
    TN: "Tunisia",
    DZ: "Algeria",
    MA: "Morocco",
    SD: "Sudan",
    SS: "South Sudan",
    ET: "Ethiopia",
    ER: "Eritrea",
    DJ: "Djibouti",
    SO: "Somalia",
    KE: "Kenya",
    UG: "Uganda",
    TZ: "Tanzania",
    RW: "Rwanda",
    BI: "Burundi",
    CG: "Congo",
    CD: "Democratic Republic of the Congo",
    CF: "Central African Republic",
    TD: "Chad",
    CM: "Cameroon",
    NG: "Nigeria",
    NE: "Niger",
    ML: "Mali",
    BF: "Burkina Faso",
    GH: "Ghana",
    TG: "Togo",
    BJ: "Benin",
    CI: "Ivory Coast",
    LR: "Liberia",
    SL: "Sierra Leone",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    SN: "Senegal",
    GM: "Gambia",
    MR: "Mauritania",
    CV: "Cape Verde",
    ST: "Sao Tome and Principe",
    GQ: "Equatorial Guinea",
    GA: "Gabon",
    AO: "Angola",
    ZM: "Zambia",
    ZW: "Zimbabwe",
    BW: "Botswana",
    NA: "Namibia",
    ZA: "South Africa",
    LS: "Lesotho",
    SZ: "Swaziland",
    MZ: "Mozambique",
    MG: "Madagascar",
    MU: "Mauritius",
    SC: "Seychelles",
    KM: "Comoros",
    MW: "Malawi",

    // South America
    BR: "Brazil",
    AR: "Argentina",
    CL: "Chile",
    PE: "Peru",
    EC: "Ecuador",
    CO: "Colombia",
    VE: "Venezuela",
    GY: "Guyana",
    SR: "Suriname",
    BO: "Bolivia",
    PY: "Paraguay",
    UY: "Uruguay",

    // Oceania
    AU: "Australia",
    NZ: "New Zealand",
    PG: "Papua New Guinea",
    FJ: "Fiji",
    SB: "Solomon Islands",
    VU: "Vanuatu",
    NC: "New Caledonia",
    WS: "Samoa",
    TO: "Tonga",
    KI: "Kiribati",
    PW: "Palau",
    MH: "Marshall Islands",
    FM: "Micronesia",
    NR: "Nauru",
    TV: "Tuvalu",

    // Caribbean
    CU: "Cuba",
    JM: "Jamaica",
    HT: "Haiti",
    DO: "Dominican Republic",
    PR: "Puerto Rico",
    TT: "Trinidad and Tobago",
    BB: "Barbados",
    VC: "Saint Vincent and the Grenadines",
    GD: "Grenada",
    LC: "Saint Lucia",
    DM: "Dominica",
    AG: "Antigua and Barbuda",
    KN: "Saint Kitts and Nevis",
    BS: "Bahamas",
  };

  return codeToNameMap[countryInput.toUpperCase()] || countryInput;
};

// Component to display country with flag
export const CountryWithFlag = ({ country }: { country: string }) => {
  const countryCode = getCountryCode(country);
  const countryName = getCountryName(country);

  return (
    <span className="inline-flex items-center gap-1.5">
      {countryCode && (
        <img
          src={`https://flagsapi.com/${countryCode}/flat/32.png`}
          alt={`${countryName} flag`}
          className="w-5 h-4 object-cover rounded-sm border border-gray-200"
          onError={(e) => {
            // Fallback to shiny style if flat fails
            const img = e.target as HTMLImageElement;
            if (img.src.includes("/flat/")) {
              img.src = `https://flagsapi.com/${countryCode}/shiny/32.png`;
            } else {
              // If both fail, hide the image
              img.style.display = "none";
            }
          }}
        />
      )}
      {countryName}
    </span>
  );
};

export { getCountryCode, getCountryName };
